import {
  VlookupConfig,
  VlookupExecutionResult,
  VlookupRowResult,
  VlookupSummaryStats
} from '@/src/types/vlookup';

/**
 * Converts 1-based column index to Excel column letter (1 -> 'A', 26 -> 'Z', 27 -> 'AA', etc.)
 */
export function colIndexToLetter(colIndex: number): string {
  let temp: number;
  let letter = '';
  while (colIndex > 0) {
    temp = (colIndex - 1) % 26;
    letter = String.fromCharCode(temp + 65) + letter;
    colIndex = Math.floor((colIndex - temp - 1) / 26);
  }
  return letter || 'A';
}

/**
 * Case-insensitive, whitespace-trimmed, and alias-safe cell accessor
 */
export function getRowValue(row: Record<string, any> | undefined | null, colName: string): any {
  if (!row || !colName) return undefined;
  if (row[colName] !== undefined && row[colName] !== null) return row[colName];

  const trimmed = colName.trim();
  if (row[trimmed] !== undefined && row[trimmed] !== null) return row[trimmed];

  const lower = trimmed.toLowerCase();
  for (const k of Object.keys(row)) {
    if (k.trim().toLowerCase() === lower) {
      return row[k];
    }
  }

  // Simplified without spaces/underscores/hyphens
  const simplified = lower.replace(/[\s\-_]+/g, '');
  for (const k of Object.keys(row)) {
    if (k.trim().toLowerCase().replace(/[\s\-_]+/g, '') === simplified) {
      return row[k];
    }
  }

  return undefined;
}

/**
 * Normalizes string keys for robust matching across spreadsheets
 */
export function normalizeKey(val: any): string {
  if (val === undefined || val === null) return '';
  let str = String(val).trim().toLowerCase();

  // Strip trailing .0 or .00 if generated by numeric Excel parsing (e.g. 101.0 -> 101)
  str = str.replace(/\.0+$/, '');

  // Strip common Ethiopian and English honorifics / titles
  str = str.replace(/^(አቶ|ወ\/ሮ|ወ\/ሪት|ወሮ|ወሪት|ዶ\/ር|ዶር|ኢ\/ር|ኢር|ፕሮፌሰር|ጋዜጠኛ|ሼክ|ሃጂ|mr\.|mrs\.|ms\.|dr\.|prof\.|eng\.|ato|w\/ro|w\/rit)\s+/i, '');

  // Normalize Ethiopic punctuation to empty
  str = str.replace(/[\u1360-\u1368]/g, '');

  // Remove non-alphanumeric separators, punctuation and brackets
  str = str.replace(/[\s\-_\\/.,:;()\[\]{}'"`]+/g, '');

  return str;
}

/**
 * Strips leading zeros for numeric identifier matching ('0042' -> '42')
 */
export function stripLeadingZeros(str: string): string {
  const stripped = str.replace(/^0+/, '');
  return stripped || '0';
}

/**
 * Bigram similarity score between two strings (0.0 to 1.0)
 */
export function calculateStringSimilarity(s1: string, s2: string): number {
  const str1 = s1.trim().toLowerCase();
  const str2 = s2.trim().toLowerCase();
  if (str1 === str2) return 1.0;
  if (!str1 || !str2) return 0.0;
  if (str1.length < 2 || str2.length < 2) return str1 === str2 ? 1.0 : 0.0;

  const getBigrams = (str: string) => {
    const bigrams = new Map<string, number>();
    for (let i = 0; i < str.length - 1; i++) {
      const b = str.substring(i, i + 2);
      bigrams.set(b, (bigrams.get(b) || 0) + 1);
    }
    return bigrams;
  };

  const b1 = getBigrams(str1);
  const b2 = getBigrams(str2);
  let intersection = 0;

  for (const [k, count1] of b1.entries()) {
    if (b2.has(k)) {
      intersection += Math.min(count1, b2.get(k)!);
    }
  }

  const total = (str1.length - 1) + (str2.length - 1);
  return (2.0 * intersection) / total;
}

/**
 * Main VLOOKUP execution engine
 */
export function executeVlookup(
  sourceRows: Record<string, any>[],
  referenceRows: Record<string, any>[],
  config: VlookupConfig
): VlookupExecutionResult {
  const startTime = performance.now();

  const sourceHeaders = sourceRows.length > 0 ? Object.keys(sourceRows[0]) : [];
  const referenceHeaders = referenceRows.length > 0 ? Object.keys(referenceRows[0]) : [];

  const refSheet = config.referenceSheetName || 'Master';
  const sourceKeyCol = config.sourceKeyColumn;
  const refKeyCol = config.referenceKeyColumn;
  const returnCols = config.returnColumns;

  // Determine Excel column coordinates
  const sourceKeyColIdx = Math.max(1, sourceHeaders.indexOf(sourceKeyCol) + 1);
  const sourceKeyColLetter = colIndexToLetter(sourceKeyColIdx);

  const refKeyColIdx = Math.max(1, referenceHeaders.indexOf(refKeyCol) + 1);
  const refKeyColLetter = colIndexToLetter(refKeyColIdx);

  const refMaxColIdx = Math.max(refKeyColIdx, ...returnCols.map(c => referenceHeaders.indexOf(c) + 1), referenceHeaders.length);
  const refMaxColLetter = colIndexToLetter(refMaxColIdx);
  const refTotalRows = referenceRows.length + 1; // including header

  // Build Reference Index Maps
  // 1. Exact map: raw string
  const exactMap = new Map<string, Record<string, any>[]>();
  // 2. Normalized map: stripped & lowercase
  const normalizedMap = new Map<string, Record<string, any>[]>();
  // 3. Numeric zero-stripped map
  const zeroStrippedMap = new Map<string, Record<string, any>[]>();

  let duplicateKeysInReference = 0;

  referenceRows.forEach(row => {
    const rawVal = getRowValue(row, refKeyCol);
    if (rawVal === undefined || rawVal === null || String(rawVal).trim() === '') return;

    const exactKey = String(rawVal).trim();
    const normKey = normalizeKey(exactKey);
    const zeroKey = stripLeadingZeros(normKey);

    // Exact map
    const exList = exactMap.get(exactKey) || [];
    exList.push(row);
    exactMap.set(exactKey, exList);
    if (exList.length === 2) duplicateKeysInReference++;

    // Normalized map
    const normList = normalizedMap.get(normKey) || [];
    normList.push(row);
    normalizedMap.set(normKey, normList);

    // Zero stripped map
    const zeroList = zeroStrippedMap.get(zeroKey) || [];
    zeroList.push(row);
    zeroStrippedMap.set(zeroKey, zeroList);
  });

  // Track duplicate keys in source
  const sourceKeyCount = new Map<string, number>();
  sourceRows.forEach(r => {
    const rawK = getRowValue(r, sourceKeyCol);
    const k = rawK !== undefined && rawK !== null ? String(rawK).trim() : '';
    if (k) sourceKeyCount.set(k, (sourceKeyCount.get(k) || 0) + 1);
  });
  let duplicateKeysInSource = 0;
  for (const count of sourceKeyCount.values()) {
    if (count > 1) duplicateKeysInSource++;
  }

  // Value for unmatched NA
  const getNaValue = () => {
    if (config.naHandling === 'custom') return config.customNaValue ?? '#N/A';
    if (config.naHandling === 'empty') return '';
    if (config.naHandling === '0') return 0;
    return config.naHandling;
  };

  const naPlaceholder = getNaValue();

  let matchedCount = 0;
  let discrepanciesCount = 0;

  // Process rows
  const rowResults: VlookupRowResult[] = sourceRows.map((sourceRow, idx) => {
    const excelRow = idx + 2; // Excel row number (1-based header)
    const rawLookupVal = getRowValue(sourceRow, sourceKeyCol);
    const lookupKey = rawLookupVal !== undefined && rawLookupVal !== null ? String(rawLookupVal).trim() : '';

    let matchedRefRow: Record<string, any> | null = null;
    let matchScore = 0;

    if (lookupKey) {
      if (config.matchMode === 'exact') {
        const matches = exactMap.get(lookupKey);
        if (matches && matches.length > 0) {
          matchedRefRow = matches[0];
          matchScore = 1.0;
        }
      } else if (config.matchMode === 'normalized') {
        // Try exact first
        const ex = exactMap.get(lookupKey);
        if (ex && ex.length > 0) {
          matchedRefRow = ex[0];
          matchScore = 1.0;
        } else {
          // Try normalized
          const normKey = normalizeKey(lookupKey);
          const normMatch = normalizedMap.get(normKey);
          if (normMatch && normMatch.length > 0) {
            matchedRefRow = normMatch[0];
            matchScore = 0.95;
          } else {
            // Try zero-stripped
            const zeroKey = stripLeadingZeros(normKey);
            const zeroMatch = zeroStrippedMap.get(zeroKey);
            if (zeroMatch && zeroMatch.length > 0) {
              matchedRefRow = zeroMatch[0];
              matchScore = 0.90;
            }
          }
        }
      } else if (config.matchMode === 'fuzzy') {
        // Try normalized first
        const normKey = normalizeKey(lookupKey);
        const normMatch = normalizedMap.get(normKey);
        if (normMatch && normMatch.length > 0) {
          matchedRefRow = normMatch[0];
          matchScore = 1.0;
        } else {
          // Search reference entries with highest similarity
          let bestScore = 0;
          let bestRow: Record<string, any> | null = null;
          const threshold = config.fuzzyThreshold ?? 0.75;

          for (const refRow of referenceRows) {
            const rawRefVal = getRowValue(refRow, refKeyCol);
            const refVal = rawRefVal !== undefined && rawRefVal !== null ? String(rawRefVal).trim() : '';
            if (!refVal) continue;
            // Compare normalized strings for higher robustness
            const sim = calculateStringSimilarity(normKey || lookupKey, normalizeKey(refVal) || refVal);
            if (sim > bestScore) {
              bestScore = sim;
              bestRow = refRow;
            }
            if (bestScore === 1.0) break;
          }

          if (bestScore >= threshold && bestRow) {
            matchedRefRow = bestRow;
            matchScore = Math.round(bestScore * 100) / 100;
          }
        }
      }
    }

    const isMatched = matchedRefRow !== null;
    if (isMatched) matchedCount++;

    const pulledValues: Record<string, any> = {};
    const formulas: Record<string, string> = {};
    const discrepancies: { column: string; sourceVal: any; lookedUpVal: any }[] = [];

    returnCols.forEach(col => {
      const alias = config.returnColumnAliases?.[col] || col;
      const lookedUpRaw = isMatched ? getRowValue(matchedRefRow!, col) : undefined;
      const val = isMatched ? (lookedUpRaw ?? '') : naPlaceholder;
      pulledValues[alias] = val;

      // Construct authentic Excel Formula
      const refColIdx = Math.max(1, referenceHeaders.indexOf(col) + 1);
      const targetColLetter = colIndexToLetter(refColIdx);

      const naArg = typeof naPlaceholder === 'string' ? `"${naPlaceholder}"` : String(naPlaceholder);
      let formula = '';
      if (config.formulaType === 'XLOOKUP') {
        formula = `=XLOOKUP(${sourceKeyColLetter}${excelRow}, '${refSheet}'!$${refKeyColLetter}$2:$${refKeyColLetter}$${refTotalRows}, '${refSheet}'!$${targetColLetter}$2:$${targetColLetter}$${refTotalRows}, ${naArg})`;
      } else if (config.formulaType === 'INDEX_MATCH') {
        formula = `=IFNA(INDEX('${refSheet}'!$${targetColLetter}$2:$${targetColLetter}$${refTotalRows}, MATCH(${sourceKeyColLetter}${excelRow}, '${refSheet}'!$${refKeyColLetter}$2:$${refKeyColLetter}$${refTotalRows}, 0)), ${naArg})`;
      } else {
        // Classic VLOOKUP: requires index relative to start of table array
        if (refColIdx >= refKeyColIdx) {
          const relColIdx = refColIdx - refKeyColIdx + 1;
          formula = `=IFNA(VLOOKUP(${sourceKeyColLetter}${excelRow}, '${refSheet}'!$${refKeyColLetter}$2:$${targetColLetter}$${refTotalRows}, ${relColIdx}, FALSE), ${naArg})`;
        } else {
          // If reference column is to the left of key column, classic VLOOKUP in Excel throws #VALUE!
          // We supply the standard Excel formula INDEX/MATCH
          formula = `=IFNA(INDEX('${refSheet}'!$${targetColLetter}$2:$${targetColLetter}$${refTotalRows}, MATCH(${sourceKeyColLetter}${excelRow}, '${refSheet}'!$${refKeyColLetter}$2:$${refKeyColLetter}$${refTotalRows}, 0)), ${naArg})`;
        }
      }
      formulas[alias] = formula;

      // Check discrepancy if source row also has this column
      const sRaw = getRowValue(sourceRow, col);
      if (sRaw !== undefined && sRaw !== null && sRaw !== '' && isMatched) {
        const sStr = String(sRaw).trim();
        const rStr = String(val ?? '').trim();
        const sNum = Number(sStr.replace(/,/g, ''));
        const rNum = Number(rStr.replace(/,/g, ''));
        const isNumMatch = !isNaN(sNum) && !isNaN(rNum) && Math.abs(sNum - rNum) < 0.001;
        const isTextMatch = sStr.toLowerCase() === rStr.toLowerCase();
        if (!isNumMatch && !isTextMatch) {
          discrepancies.push({
            column: col,
            sourceVal: sRaw,
            lookedUpVal: val
          });
        }
      }
    });

    if (discrepancies.length > 0) {
      discrepanciesCount++;
    }

    return {
      rowIndex: idx,
      excelRowNumber: excelRow,
      originalRow: sourceRow,
      lookupKey,
      isMatched,
      matchScore: isMatched ? matchScore : 0,
      matchedReferenceRow: matchedRefRow,
      pulledValues,
      formulas,
      hasDiscrepancies: discrepancies.length > 0,
      discrepancies
    };
  });

  const totalRows = sourceRows.length;
  const unmatchedCount = totalRows - matchedCount;
  const matchRatePercent = totalRows > 0 ? Math.round((matchedCount / totalRows) * 1000) / 10 : 0;
  const executionTimeMs = Math.round((performance.now() - startTime) * 10) / 10;

  const outputHeaders = [
    ...sourceHeaders,
    ...returnCols.map(col => config.returnColumnAliases?.[col] || col)
  ];

  // Sample Formula for first return column
  const firstReturnCol = returnCols[0] || '';
  const firstReturnAlias = config.returnColumnAliases?.[firstReturnCol] || firstReturnCol;
  const sampleFormula = rowResults[0]?.formulas[firstReturnAlias] || `=IFNA(VLOOKUP(A2, '${refSheet}'!$A$2:$H$5000, 2, FALSE), "Not Found")`;

  const summary: VlookupSummaryStats = {
    totalRows,
    matchedCount,
    unmatchedCount,
    matchRatePercent,
    duplicateKeysInReference,
    duplicateKeysInSource,
    executionTimeMs,
    discrepanciesCount
  };

  return {
    config,
    sourceHeaders,
    referenceHeaders,
    outputHeaders,
    rows: rowResults,
    summary,
    sampleFormula,
    referenceRows
  };
}
